version: '3.9'
services:
  nginx-prod:
    image: "${DOCKER_HUB_NICKNAME}/private:${COMPOSE_PROJECT_NAME}-nginx-prod"
    restart: always
    depends_on:
      - backend-prod
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
      target: prod_nginx_with_front_static
      args:
        - REACT_APP_NAME=${COMPOSE_PROJECT_NAME}
    environment:
      - TZ=${TZ}
      - GENERATE_SOURCEMAP=${GENERATE_SOURCEMAP}
      - INNER_NGINX_HTTP_PORT=${INNER_NGINX_HTTP_PORT}
      - EXTERNAL_NGINX_HTTP_PORT=${EXTERNAL_NGINX_HTTP_PORT}
      - INNER_BACKEND_HTTP_SERVER_PORT=${INNER_BACKEND_HTTP_SERVER_PORT}
      - INNER_BACKEND_WS_SERVER_PORT=${INNER_BACKEND_WS_SERVER_PORT}
    ports:
      - ${EXTERNAL_NGINX_HTTP_PORT}:${INNER_NGINX_HTTP_PORT}/tcp
#      - ${EXTERNAL_NGINX_HTTPS_PORT}:${INNER_NGINX_HTTPS_PORT}/tcp
    networks:
      nginx-back-net-prod:
      nginx-pgadmin-net-prod:
        ipv4_address: 10.5.0.2

    # volumes:
    #   - ./data/certbot/conf:/etc/letsencrypt
    #   - ./data/certbot/www:/var/www/certbot

  # certbot:
  #   image: certbot/certbot
  #   command: certonly -n -d local.host --webroot --agree-tos --email kolya007.klass@gmail.com -w /var/www/certbot
  #   volumes:
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot
  #     - ./data/certbot/logs:/var/log/letsencrypt/

  backend-prod:
    image: "${DOCKER_HUB_NICKNAME}/private:${COMPOSE_PROJECT_NAME}-backend-prod"
    restart: always
    depends_on:
      - postgres-prod
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
      target: production
      args:
        - INNER_BACKEND_HTTP_SERVER_PORT=${INNER_BACKEND_HTTP_SERVER_PORT}
        - INNER_BACKEND_WS_SERVER_PORT=${INNER_BACKEND_WS_SERVER_PORT}
    environment:
      - TZ=${TZ}
      - NODE_ENV=production
      - SERVER_PORT=${INNER_BACKEND_HTTP_SERVER_PORT}
      - WEB_SOCKET_SERVER_PORT=${INNER_BACKEND_WS_SERVER_PORT}
      - WEB_SOCKET_SERVER_PATH=${WEB_SOCKET_SERVER_PATH}
      - BOOTSTRAP_MODE=${BOOTSTRAP_MODE}
      - MOCK_SCRIPT_NAME=${MOCK_SCRIPT_NAME}
      - AUTH_JWT_SECRET=${AUTH_JWT_SECRET}
      - USER_PASSWORD_HASH_SALT=${USER_PASSWORD_HASH_SALT}
      - INVITE_USERS_SIGN_KEY=${INVITE_USERS_SIGN_KEY}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_TYPEORM_LOGGING_MODE=${DATABASE_TYPEORM_LOGGING_MODE}
    volumes:
      - type: bind # for running migrate script inside existing backend container
        source: ./backend/src/modules/infrastructure/
        target: /app/src/modules/infrastructure/
    networks:
      nginx-back-net-prod:
      back-db-net-prod:

  postgres-prod:
    image: postgres
    restart: always
    command: "-c default_text_search_config=pg_catalog.russian"
    environment:
      - TZ=${TZ}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - type: volume
        source: postgres-prod-data
        target: /var/lib/postgresql/data
#    ports:
#      - 5400:${DATABASE_PORT}
    networks:
      back-db-net-prod:
      pgadmin-db-net-prod:

  postgres-admin-prod:
    image: dpage/pgadmin4:latest
    restart: always
    depends_on:
      - postgres-prod
    profiles:
      - use_pg_admin_tool
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      nginx-pgadmin-net-prod:
        ipv4_address: 10.5.0.3
      pgadmin-db-net-prod:

volumes:
  postgres-prod-data:

# when i will really want to use https and ssl
# article how to setup certbot and let's encrypt
# https://pentacent.medium.com/nginx-and-lets-encrypt-with-docker-in-less-than-5-minutes-b4b8a60d3a71
# online nginx configuration
# https://www.digitalocean.com/community/tools/nginx
# TODO: research posibility to use serial device and run smarthouse
# https://www.losant.com/blog/how-to-access-serial-devices-in-docker

networks:
  nginx-back-net-prod: {}
  nginx-pgadmin-net-prod:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
  back-db-net-prod: {}
  pgadmin-db-net-prod: {}
