version: '3.9'
services:
  vscode-devcontainer:
    image: mcr.microsoft.com/devcontainers/typescript-node:18
    command: sleep infinity
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - INNER_DEV_FRONT_LIVE_RELOAD_SERVER_PORT=${INNER_DEV_FRONT_LIVE_RELOAD_SERVER_PORT}
      - DEV_BACKEND_DEBUGGER_PORT=${DEV_BACKEND_DEBUGGER_PORT}
      - TSC_WATCHFILE=UseFsEvents
    volumes:
      - type: bind
        source: ../
        target: "/workspaces/${COMPOSE_PROJECT_NAME}"
        consistency: delegated
      - type: bind
        source: ../shared/src/types/shared
        target: "/workspaces/${COMPOSE_PROJECT_NAME}/frontend/src/types/shared"
        consistency: delegated
      - type: bind
        source: ../shared/src/types/shared
        target: "/workspaces/${COMPOSE_PROJECT_NAME}/backend/src/types/shared"
        consistency: delegated
      - type: bind
        source: ../shared/src/tools/shared
        target: "/workspaces/${COMPOSE_PROJECT_NAME}/frontend/src/tools/shared"
        consistency: delegated
      - type: bind
        source: ../shared/src/tools/shared
        target: "/workspaces/${COMPOSE_PROJECT_NAME}/backend/src/tools/shared"
        consistency: delegated
    networks:
      vscode-back-net-dev:
      vscode-db-net-dev:
      vscode-front-net-dev:
networks:
  vscode-back-net-dev: {}
  vscode-db-net-dev: {}
  vscode-front-net-dev: {}
