export enum ConfigKeys {
  BOOTSTRAP_MODE = 'bootstrapMode',
  DATABASE_HOST = 'databaseHost',
  DATABASE_NAME = 'databaseName',
  DATABASE_PASSWORD = 'databasePassword',
  DATABASE_PORT = 'databasePort',
  DATABASE_TYPEORM_LOGGING_MODE = 'databaseLoggingMode',
  DATABASE_USERNAME = 'databaseUsername',
  IS_DEVELOPMENT = 'isDevelopment',
  AUTH_JWT_SECRET = 'authJwtSecret',
  USER_PASSWORD_HASH_SALT = 'userPasswordHashSalt',
  IS_PRODUCTION = 'isProduction',
  MOCK_SCRIPT_NAME = 'mockScriptName',
  SERVER_PORT = 'serverPort',
  WEB_SOCKET_SERVER_PORT = 'webSocketServerPort',
  INVITE_USERS_SIGN_KEY = 'inviteUsersSignKey',
}
