export enum ConfigKeys {
  DATABASE_HOST = 'databaseHost',
  DATABASE_NAME = 'databaseName',
  DATABASE_PASSWORD = 'databasePassword',
  DATABASE_PORT = 'databasePort',
  DATABASE_TYPEORM_LOGGING_MODE = 'databaseLoggingMode',
  DATABASE_USERNAME = 'databaseUsername',

  BOOTSTRAP_MODE = 'bootstrapMode',
  IS_DEVELOPMENT = 'isDevelopment',
  IS_PRODUCTION = 'isProduction',
  IS_SERVICE_HELPER_ONLY_MODE = 'isServiceHelperOnlyMode',
  MOCK_SCRIPT_NAME = 'mockScriptName',
  ENABLE_SWAGGER_IN_PROD = 'enableSwaggerInProd',
  SERVER_PORT = 'serverPort',
  WEB_SOCKET_SERVER_PORT = 'webSocketServerPort',
  WEB_SOCKET_SERVER_PATH = 'webSocketServerPath',
  TOKEN_PAIR_COOKIE_CONFIG = 'tokenPairCookieConfig',

  AUTH_JWT_SECRET = 'authJwtSecret',
  USER_PASSWORD_HASH_SALT_SECRET = 'userPasswordHashSaltSecret',
  INVITE_USERS_SIGN_KEY_SECRET = 'inviteUsersSignKeySecret',
  COOKIE_SIGN_KEY_SECRET = 'cookieSignKeySecret',
  GOOGLE_OAUTH_TOKEN_SECRET = 'googleOAuthTokenSecret',

  REDIS_MASTER_PORT = 'redisMasterPort',
  REDIS_MASTER_HOST = 'redisMasterHost',
  REDIS_MASTER_PASSWORD = 'redisMasterPassword',
  REDIS_REPLICA_PORT = 'redisReplicaPort',
  REDIS_REPLICA_HOST = 'redisReplicaHost',
  REDIS_REPLICA_PASSWORD = 'redisReplicaPassword',
}
