export enum Currency {
  XCD = 'xcd',
  BBD = 'bbd',
  USD = 'usd',
  CNY = 'cny',
  COP = 'cop',
  CRC = 'crc',
  DOP = 'dop',
  GTQ = 'gtq',
  HNL = 'hnl',
  HKD = 'hkd',
  JMD = 'jmd',
  NIO = 'nio',
  PYG = 'pyg',
  PEN = 'pen',
  EUR = 'eur',
  TWD = 'twd',
  TTD = 'ttd',
  MXN = 'mxn',
  RUB = 'rub',
  CZK = 'czk',
}
