#!/bin/bash

export TZ='Europe/Moscow'
export COMPOSE_PROJECT_NAME='boilerplate'
export DOCKER_BUILDKIT=1

# frontend
export DANGEROUSLY_DISABLE_HOST_CHECK='true'
# should be false on production
export GENERATE_SOURCEMAP='true'

# backend

# 'production' | 'development'
# export NODE_ENV=

# Don`t forget to change to another long secure random string in production
# It`s key for sign jwt auth tokens
export JWT_SECRET='[a0oej4rgip5g0aijefogpihn[4ijks;wk3f3ihgposldckdieselkwn5 vlkfj[q34t"k:\"KP_FF\"#ORKOWI:EJLEDK_@#sKOJGWRLGNK<ASJDN:EWLGKJWOIJWOLFJKNDSMNGSG>SNFELK<NSFMNSDLKGJBNO:FLKWEMF}}]]]'

# Don`t forget to change to another long secure random string in production
# It`s a part of salt for generating user password hashes
export USER_PASSWORD_HASH_SALT='[ijwefleskemdlckajsrnoe-]50w[4-g3q[4gi-0[wjeirgvsloij;b[-q304ihjilosekrgmoit;ehkgm zsj.dne,smjrmnf]]]]]'

export MOCK_SCRIPT_NAME='fillDBScript'

# 'mock' | 'endpoints' | 'mockAndEndpoints'
export BOOTSTRAP_MODE='mockAndEndpoints'

# database
# export DATABASE_HOST=
export DATABASE_PORT='5432'
export DATABASE_USERNAME='pgdockeruser'
export DATABASE_PASSWORD='pgdockerpass'
export DATABASE_NAME='pgdockeruserdatabase'
# JSON of (true | false | 'all' | ('query' | 'schema' | 'error' | 'warn' | 'info' | 'log' | 'migration')[])
export DATABASE_TYPEORM_LOGGING_MODE='"all"'

# pgadmin vars
export PGADMIN_DEFAULT_EMAIL='admin@hello.com'
export PGADMIN_DEFAULT_PASSWORD='password'

# development ports
export DEV_BACKEND_DEBUGGER_PORT='9229'


#universal ports
export INNER_BACKEND_HTTP_SERVER_PORT='3001'
export INNER_BACKEND_WS_SERVER_PORT='3002'

export INNER_NGINX_HTTPS_PORT='443'
export INNER_NGINX_HTTP_PORT='80'

export EXTERNAL_NGINX_HTTP_PORT='5001'
export EXTERNAL_NGINX_HTTPS_PORT='5002'
